### ISSUE TITLE
Wrong answers are correct?

### ISSUE THREAD

**Issue by Max-H-0** [duck-dev/VocabularyTrainer#2]
Some answers are accepted as correct even though they're not, is that a bug or feature incase its close?
How can I disable it incase it's intendet?

**Comment by duck-dev** [comment]
@Max-H-0 You can adjust the error tolerance with various parameters when creating a new or editing an existing lesson (see the the 3 images below). As you can see in image 3, there are 3 default presets ("High", "Balanced", "Low") and a "Custom" option. If this is selected, you can adjust the parameters below however you like. "Low" means 0 tolerance, so the answer has to match the definition, also considering punctuation, capitalization, accent marks, hyphens etc.

![Error_Tolerance_Creating-Lesson](https://user-images.githubusercontent.com/61479436/233785782-ef9d153f-06c3-425c-a8b9-b3501735dee1.png)
![Error_Tolerance_Editing-Lesson png](https://user-images.githubusercontent.com/61479436/233785784-2e29ca66-0d10-4eee-93a5-76836e2c72b1.png)
![lesson-options](https://user-images.githubusercontent.com/61479436/233785799-ceea3f2e-d8d0-475c-9c9d-4a1c0c47ab72.png)

**Comment by Max-H-0** [comment]
Thank you!
